"""The main library view: mod artwork and status first, settings within reach."""
import os
import tkinter as tk
from tkinter import ttk, messagebox

from app_config import APP_VERSION, CONCURRENCY_CHOICES, BATCH_SIZE_CHOICES
from translation_cost import PRICING_NOTE


def build_view(app):
    app.geometry('1120x880')
    app.minsize(940, 780)
    style = ttk.Style(app)
    style.theme_use('clam')
    style.configure('.', font=('Segoe UI', 10))
    style.configure('TFrame', background='#f5f6fa')
    style.configure('TLabel', background='#f5f6fa', foreground='#24324b')
    style.configure('Title.TLabel', font=('Segoe UI', 25, 'bold'), foreground='#17213c')
    style.configure('Sub.TLabel', foreground='#64748b')
    style.configure('Card.TFrame', background='white')
    style.configure('Card.TLabel', background='white', foreground='#24324b')
    style.configure('TButton', padding=(12, 7), borderwidth=0)
    style.configure('Action.TButton', font=('Segoe UI', 12, 'bold'), padding=(20, 13),
                    foreground='white', background='#385ee8')
    style.map('Action.TButton', background=[('disabled', '#bcc6e8'), ('active', '#2446c2')])
    style.configure('Treeview', font=('Segoe UI', 10), rowheight=66, borderwidth=0,
                    background='white', fieldbackground='white', foreground='#24324b')
    style.configure('Treeview.Heading', font=('Segoe UI', 9, 'bold'), padding=10, background='#edf1f7')
    style.map('Treeview', background=[('selected', '#e7edff')], foreground=[('selected', '#2446c2')])
    menu = tk.Menu(app)
    options = tk.Menu(menu, tearoff=False)
    for label, command in [('Choose game folder…', app.choose_game), ('Refresh mods', app.refresh),
                           ('Check game setup', app.start_setup), ('Collect logs', app.collect_logs),
                           ('API key…', app.api_key_settings), ('GitHub access…', app.github_settings),
                           ('Check for updates', lambda: app.check_updates(manual=True)),
                           ('Refresh shared translations', app.refresh_shared),
                           ('Find untranslated destinies', app.find_destinies)]:
        options.add_command(label=label, command=command)
    options.add_command(label='About cost estimates…', command=lambda: messagebox.showinfo('Cost estimates', PRICING_NOTE))
    options.add_separator()
    for label, command in [('Translation editor…', app.editor), ('Open saved translations', app.open_folder),
                           ('Install saved translations', app.install_saved),
                           ('Translate selected mod again…', app.retranslate_selected),
                           ('Translate selected title again', app.retranslate_title),
                           ('Remove selected mod’s translations', app.remove_installed)]:
        options.add_command(label=label, command=command)
    menu.add_cascade(label='Options', menu=options)
    app.configure(menu=menu)
    body = ttk.Frame(app, padding=(24, 18))
    body.pack(fill='both', expand=True)
    header = ttk.Frame(body)
    header.pack(fill='x', pady=(0, 18))
    heading = ttk.Frame(header)
    heading.pack(side='left', fill='x', expand=True)
    ttk.Label(heading, text='Your mod library', style='Title.TLabel').pack(anchor='w')
    ttk.Label(heading, text=('Friends' if app.friends else 'Personal') + ' · ' + APP_VERSION + ' · English translations for Tale of Immortal', style='Sub.TLabel').pack(anchor='w', pady=(4, 0))
    balance = ttk.Frame(header)
    balance.pack(side='right')
    ttk.Label(balance, textvariable=app.balance_label, font=('Segoe UI', 13, 'bold')).pack(anchor='e')
    ttk.Label(balance, textvariable=app.balance_detail, style='Sub.TLabel').pack(anchor='e')
    app.api_key_button = ttk.Button(balance, text='API key…', command=app.api_key_settings)
    app.api_key_button.pack(side='right', pady=(5, 0))
    from api_key_dialog import help_link
    app.api_help_button = help_link(balance, app)
    app.api_help_button.pack(side='right', padx=8)
    update = ttk.Frame(body)
    update.pack(fill='x')
    ttk.Label(update, textvariable=app.update_status, style='Sub.TLabel').pack(side='left')
    app.update_button = ttk.Button(update, text='Install update…', command=app.install_update)
    search = ttk.Frame(body)
    search.pack(fill='x', pady=(8, 10))
    ttk.Label(search, text='Find a mod', style='Sub.TLabel').pack(side='left', padx=(0, 10))
    ttk.Entry(search, textvariable=app.search, font=('Segoe UI', 11)).pack(side='left', fill='x', expand=True)
    ttk.Button(search, text='Refresh', command=app.refresh).pack(side='left', padx=(10, 0))
    app.library_count = tk.StringVar()
    ttk.Label(search, textvariable=app.library_count, style='Sub.TLabel').pack(side='right', padx=12)
    app.search.trace_add('write', lambda *_: app.render())
    controls = ttk.Frame(body)
    controls.pack(side='bottom', fill='x')
    content = ttk.Frame(body)
    content.pack(fill='both', expand=True)
    list_frame = ttk.Frame(content)
    list_frame.pack(side='left', fill='both', expand=True)
    app.list = ttk.Treeview(list_frame, columns=('cost', 'access'), show='tree headings', selectmode='browse', height=5)
    app.list.heading('#0', text='MOD')
    app.list.heading('cost', text='ESTIMATE')
    app.list.heading('access', text='STATUS')
    app.list.column('#0', width=335, minwidth=170)
    app.list.column('cost', width=100, minwidth=90, stretch=False, anchor='e')
    app.list.column('access', width=145, minwidth=125, stretch=False)
    scroll = ttk.Scrollbar(list_frame, orient='vertical', command=app.list.yview)
    app.list.configure(yscrollcommand=scroll.set)
    app.list.pack(side='left', fill='both', expand=True)
    scroll.pack(side='right', fill='y')
    app.list.bind('<<TreeviewSelect>>', app.selected)
    detail = ttk.Frame(content, padding=16, style='Card.TFrame', width=260)
    detail.pack(side='right', fill='y', padx=(14, 0))
    ttk.Button(detail, text='Install saved translations', command=app.install_saved).pack(side='bottom', fill='x', pady=(5, 0))
    app.detail_image = ttk.Label(detail, text='Select a mod', anchor='center', style='Card.TLabel')
    app.detail_image.pack(fill='x', pady=(0, 12))
    app.detail_name = tk.StringVar(value='Ready when you are')
    app.detail_original = tk.StringVar()
    app.detail_meta = tk.StringVar(value='Choose a mod to view its saved progress and translation options.')
    app.detail_saved = tk.StringVar()
    for variable, font in [(app.detail_name, ('Segoe UI', 14, 'bold')), (app.detail_original, ('Segoe UI', 9)),
                           (app.detail_meta, ('Segoe UI', 10)), (app.detail_saved, ('Segoe UI', 10))]:
        ttk.Label(detail, textvariable=variable, wraplength=220, style='Card.TLabel', font=font).pack(anchor='w', pady=3)
    ttk.Label(controls, textvariable=app.title_status, style='Sub.TLabel', wraplength=980).pack(anchor='w', pady=(5, 0))
    app.choose = ttk.Button(controls, text='Choose game folder…', command=app.choose_game)
    settings = ttk.Frame(controls)
    settings.pack(fill='x', pady=(10, 0))
    ttk.Label(settings, text='Translation settings', font=('Segoe UI', 10, 'bold')).pack(side='left')
    ttk.Label(settings, text='Parallel requests', style='Sub.TLabel').pack(side='left', padx=(20, 6))
    app.parallel = ttk.Combobox(settings, textvariable=app.concurrency, values=CONCURRENCY_CHOICES, state='readonly', width=5)
    app.parallel.pack(side='left')
    app.parallel.bind('<<ComboboxSelected>>', app.change_concurrency)
    ttk.Label(settings, text='Entries per request', style='Sub.TLabel').pack(side='left', padx=(18, 6))
    app.batch_choice = ttk.Combobox(settings, textvariable=app.batch_size, values=BATCH_SIZE_CHOICES, state='readonly', width=5)
    app.batch_choice.pack(side='left')
    app.batch_choice.bind('<<ComboboxSelected>>', app.change_batch_size)
    app.title_again_button = ttk.Button(settings, text='Title again', command=app.retranslate_title)
    app.title_again_button.pack(side='right')
    app.again_button = ttk.Button(settings, text='Translate mod again…', command=app.retranslate_selected)
    app.again_button.pack(side='right', padx=8)
    bulk = ttk.Frame(controls)
    bulk.pack(fill='x', pady=(10, 0))
    app.bulk_button = ttk.Button(bulk, text='Translate all', command=app.translate_all)
    app.bulk_button.pack(side='left')
    app.price_slider = tk.Scale(bulk, from_=5, to=200, resolution=5, orient='horizontal', variable=app.bulk_price,
                                command=app.change_bulk_price, showvalue=False, highlightthickness=0, bg='#f5f6fa', bd=0)
    app.price_slider.pack(side='left', fill='x', expand=True, padx=10)
    ttk.Label(bulk, textvariable=app.bulk_price_label, width=22).pack(side='right')
    ttk.Label(controls, textvariable=app.bulk_note, style='Sub.TLabel', wraplength=960).pack(anchor='w', pady=3)
    app.action = ttk.Button(controls, text='Translate and install', style='Action.TButton', command=app.translate)
    app.action.pack(fill='x', pady=(10, 8))
    app.action.state(['disabled'])
    app.bar = ttk.Progressbar(controls, mode='indeterminate')
    app.status_label = ttk.Label(controls, textvariable=app.status, wraplength=980)
    app.status_label.pack(anchor='w', pady=(4, 8))
    body.bind('<Configure>', lambda event: app.status_label.configure(wraplength=max(240, event.width - 50)))
    app.result_button = ttk.Button(controls, text='Open translations', command=app.open_folder)
    app.setup_retry = ttk.Button(controls, text='Retry setup', command=app.start_setup)
    app.steam_install = ttk.Button(controls, text='Install game in Steam', command=lambda: os.startfile('steam://install/1468810'))
    footer = ttk.Frame(controls)
    footer.pack(fill='x')
    app.destiny_button = ttk.Button(footer, text='Find destinies', command=app.find_destinies)
    app.destiny_button.pack(side='left')
    app.translate_destiny_button = ttk.Button(footer, text='Translate destiny menu', command=app.translate_destinies)
    app.translate_destiny_button.pack(side='left', padx=8)
    app.logs_button = ttk.Button(footer, text='Collect logs', command=app.collect_logs)
    app.logs_button.pack(side='left')
    ttk.Label(footer, textvariable=app.log_status, style='Sub.TLabel', wraplength=220).pack(side='left', padx=8)
    app.play_button = ttk.Button(footer, text='Launch game', command=app.play)
    app.play_button.pack(side='right')
    ttk.Label(controls, text='Saved translations are reused. Restart the game after installing changes.', style='Sub.TLabel').pack(anchor='w', pady=(8, 0))
