import copy
import csv
import hashlib
import json
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from extractor import *
from translation import protect, restore, translate


class WorkflowTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.base = Path(self.temp.name)
        self.mod = self.base / 'mod'
        self.mod.mkdir()
        self.info = {'id': 'fixture', 'name': '测试模组', 'path': str(self.mod), 'origin': 'test'}
        self.output = self.base / 'output'

    def write(self, name, obj, encrypted=False):
        path = self.mod / name
        path.parent.mkdir(parents=True, exist_ok=True)
        data = json.dumps(obj, ensure_ascii=False).encode()
        if encrypted:
            data = MAGIC + bytes((v + MOD_KEY[i % len(MOD_KEY)]) & 255 for i, v in enumerate(data))
        path.write_bytes(data)
        return path

    def test_known_cipher_and_encodings(self):
        # Fixed sample, not generated by the test's encoder.
        self.assertEqual(decode(MAGIC + bytes.fromhex('87'),), '[')
        self.assertEqual(decode('恢复灵力'.encode('gb18030')), '恢复灵力')
        self.assertEqual(decode('恢复灵力'.encode('utf-16')), '恢复灵力')

    def test_comments_and_trailing_comma_preserve_literal_text(self):
        source = '//备注\n[{"ch":"说明 // https://example.com/a,} ", /* 内部 */ "id":1,},]'
        self.assertEqual(mod_json(source), [{'ch': '说明 // https://example.com/a,} ', 'id': 1}])
        with self.assertRaises(ValueError): mod_json('{"ch":')

    def test_encrypted_cache_loose_tables_dedup_and_references(self):
        row = {'id': 7, 'key': 'item_desc_7', 'ch': '<r>恢复灵力</r> {0}', 'tc': '<r>恢复灵力</r> {0}'}
        path = self.write('ModExportData.cache', {'items': {'LocalText': [row], 'ItemProps': [{'id': 4, 'desc': 'item_desc_7'}]}}, True)
        before = hashlib.sha256(path.read_bytes()).hexdigest()
        self.write('ModExcel/LocalText.json', [row], True)
        p = extract(self.info, self.output)
        self.assertEqual(len(p['units']), 1)
        u = p['units'][0]
        self.assertEqual(len(u['occurrences']), 4)
        self.assertEqual(u['category'], 'player_text')
        self.assertEqual(u['referenced_by'][0]['row_id'], '4')
        self.assertEqual(before, hashlib.sha256(path.read_bytes()).hexdigest())

    def test_nested_json_unicode_single_character_and_technical_fields(self):
        self.write('data.json', {'payload': json.dumps({'message': '剑'}, ensure_ascii=True), 'icon': '图标.png'})
        p = extract(self.info, self.output)
        units = {u['source']: u for u in p['units']}
        self.assertEqual(units['剑']['category'], 'player_text')
        self.assertEqual(units['图标.png']['category'], 'technical')

    def test_rescan_preserves_manual_work_and_archives_removed_translations(self):
        path = self.write('items.json', {'name': '剑', 'desc': '恢复灵力'})
        p = extract(self.info, self.output)
        for u in p['units']: u.update(translation='Sword' if u['source'] == '剑' else 'Restore spirit', status='edited')
        save_project(p, self.output)
        path.write_text('{"name":"剑"}', encoding='utf-8')
        again = extract(self.info, self.output)
        self.assertEqual(again['units'][0]['translation'], 'Sword')
        self.assertEqual(again['retired_units'][0]['translation'], 'Restore spirit')
        self.assertTrue((self.output/'project.previous.json').is_file())

    def test_csv_multiline_roundtrip_and_atomic_validation(self):
        self.write('items.json', {'name': '剑', 'desc': '你好,\n<r>世界</r> {0}'})
        p = extract(self.info, self.output)
        translations = {'剑': 'Sword', '你好,\n<r>世界</r> {0}': 'Hello,\n<r>world</r> {0}'}
        for u in p['units']: u['translation'] = translations[u['source']]
        path = self.base/'translated.csv'
        export_csv(p, path)
        blank = copy.deepcopy(p)
        for u in blank['units']: u['translation'] = ''
        self.assertEqual(import_csv(blank, path), 2)
        self.assertEqual({u['source']:u['translation'] for u in blank['units']}, translations)
        with path.open(encoding='utf-8-sig', newline='') as f: rows = list(csv.DictReader(f))
        rows[-1]['source'] = '来源被修改'
        with path.open('w', encoding='utf-8-sig', newline='') as f:
            w=csv.DictWriter(f, fieldnames=rows[0].keys()); w.writeheader(); w.writerows(rows)
        unchanged = copy.deepcopy(blank)
        with self.assertRaises(ValueError): import_csv(blank, path)
        self.assertEqual(blank, unchanged)

    def test_placeholder_integrity_and_mask_roundtrip(self):
        source = '<color=#ff0000>获得{0}个剑</color>\\n[NAME] %s \\V[1]'
        masked, tokens = protect(source)
        self.assertEqual(restore(masked, tokens), source)
        self.assertTrue(validate_translation(source, 'Get sword'))
        self.assertFalse(validate_translation(source, source.replace('获得', 'Get ').replace('个剑', ' swords')))
        collision = '获得\\V[900001]<r>剑</r>'
        masked, tokens = protect(collision)
        self.assertEqual(restore(masked, tokens), collision)

    def test_unreadable_duplicate_and_media_are_reported(self):
        (self.mod/'broken.json').write_text('{"ch":', encoding='utf-8')
        (self.mod/'duplicate.json').write_text('{"ch":', encoding='utf-8')
        (self.mod/'lettering.png').write_bytes(b'fixture')
        p = extract(self.info, self.output)
        self.assertEqual(p['coverage']['counts']['unreadable'], 2)
        self.assertEqual(p['coverage']['counts']['media_review'], 1)
        self.assertFalse(p['coverage']['complete_player_text_coverage'])

    def test_spreadsheet_blank_cells_do_not_hide_later_rows(self):
        import openpyxl
        book = openpyxl.Workbook()
        sheet = book.active
        sheet['A1'], sheet['E5'] = '剑', '宝物说明'
        book.save(self.mod/'LocalText.xlsx')
        book.close()
        p = extract(self.info, self.output)
        self.assertEqual({u['source'] for u in p['units']}, {'剑', '宝物说明'})
        self.assertEqual(p['coverage']['counts'], {'scanned': 1})

    def test_cancellation_preserves_previous_project(self):
        self.write('items.json', {'name':'剑'})
        extract(self.info, self.output)
        before = (self.output/'project.json').read_bytes()
        with self.assertRaises(InterruptedError): extract(self.info, self.output, stop=lambda: True)
        self.assertEqual(before, (self.output/'project.json').read_bytes())

    def test_source_comments_are_excluded(self):
        (self.mod/'ui.cs').write_bytes('//内部注释\nvar a = "显示提示"; /*隐藏注释*/\nvar b=@"多行\n文字";'.encode('utf-8'))
        p = extract(self.info, self.output)
        self.assertEqual({u['source'] for u in p['units']}, {'显示提示', '多行\n文字'})

    def test_existing_english_and_spreadsheet_schema(self):
        import openpyxl
        book = openpyxl.Workbook()
        sheet = book.active
        sheet.append(['id', 'key', 'ch', 'en'])
        sheet.append(['int', 'string', 'string', 'string'])
        sheet.append([1, 'item1', '剑', 'Sword'])
        sheet.append([2, 'item2', '<r>灵力</r>', 'Spirit'])
        book.save(self.mod/'LocalText.xlsx')
        book.close()
        p = extract(self.info, self.output)
        units = {u['source']:u for u in p['units']}
        self.assertEqual(units['剑']['translation'], 'Sword')
        self.assertEqual(units['剑']['status'], 'existing')
        self.assertEqual(units['剑']['category'], 'player_text')
        self.assertEqual(units['<r>灵力</r>']['translation'], '')

    def test_translation_pipeline_with_mock_deepseek_transport(self):
        from unittest.mock import patch
        self.write('items.json', {'desc': '<r>灵力</r>{0}'})
        p = extract(self.info, self.output)
        requests = []
        def fake_http(request, timeout):
            payload = json.loads(request.data)
            requests.append((payload['model'], request.full_url))
            sources = json.loads(payload['messages'][1]['content'])
            content = json.dumps([s.replace('灵力', 'Spirit') for s in sources])
            return io.BytesIO(json.dumps({'choices':[{'message':{'content':content}}]}).encode())
        profile = {'api_key':'test', 'provider':'DeepSeek', 'model':'deepseek-flash', 'endpoint':'https://api.deepseek.com/v1/chat/completions'}
        with patch('translation.service_profile', return_value=profile), patch('translation.urllib.request.urlopen', fake_http):
            result = translate(p, self.output)
        self.assertTrue(requests)
        self.assertTrue(all(r == ('deepseek-flash', 'https://api.deepseek.com/v1/chat/completions') for r in requests))
        self.assertEqual(result['translated'], 1)
        self.assertEqual(p['units'][0]['model'], 'deepseek-flash')
        self.assertEqual(p['units'][0]['translation'], '<r>Spirit</r>{0}')
        self.assertEqual(read_json(self.output/'dictionary.json'), {'<r>灵力</r>{0}':'<r>Spirit</r>{0}'})

    def test_bad_markers_are_not_saved_as_translations(self):
        from unittest.mock import patch
        self.write('items.json', {'desc':'<r>灵力</r>{0}'})
        p = extract(self.info, self.output)
        with patch('translation.service_profile', return_value={}), patch('translation.request_batch', return_value=['Spirit']):
            result = translate(p, self.output)
        self.assertEqual(result['failed'], 1)
        self.assertEqual(read_json(self.output/'dictionary.json'), {})

    def test_failed_service_keeps_prior_translation(self):
        from unittest.mock import patch
        from translation import TranslationError
        self.write('items.json', [{'name':'剑'},{'name':'灵力'}])
        p = extract(self.info, self.output)
        p['units'][0]['translation']='Existing edit'
        with patch('translation.service_profile', return_value={}), patch('translation.request_batch', side_effect=TranslationError('Allowance exhausted')):
            with self.assertRaises(TranslationError):
                translate(p, self.output)
        saved = read_json(self.output/'project.json')
        self.assertEqual(saved['units'][0]['translation'], 'Existing edit')

    def test_one_button_never_calls_partial_work_success(self):
        from unittest.mock import patch
        from mod_workflow import run_job
        self.write('items.json', {'desc':'灵力'})
        with patch('translation.service_profile', return_value={}), patch('translation.request_batch', return_value=['灵力']):
            result = run_job(self.info, self.output, lambda _:None, lambda:False)
        self.assertEqual(result['state'], 'partial')
        self.assertEqual(result['pending'], 1)


if __name__ == '__main__': unittest.main()
